"""監査結果を配布可能なレポート(Markdown / PDF)に変換する。

画面(static/app.js)と同じ用語・同じ並びで出す。画面と用語がずれると、
受け取った人が別の指標だと誤解するため、ラベルはここに二重定義せず
画面と同じ文言を意識的に写している(変更時は両方直す)。

PDFのフォントは **埋め込み必須**。reportlabの内蔵CIDフォント(HeiseiKakuGo-W5)は
PDFに埋め込まれず閲覧側のフォントに依存するため、日本語は出ても英数字が豆腐になる
環境がある(2026-08-03に実測)。配布物なので IPAexGothic(TrueType)を埋め込む。
Noto Sans CJK はPostScriptアウトラインでreportlabが埋め込めないため使えない。
"""

from __future__ import annotations

import datetime
import io
import os
import re
from typing import Any

JST = datetime.timezone(datetime.timedelta(hours=9))

CATEGORY_LABELS = {
    "ja": {
        "robots": "AIクローラー",
        "llms": "llms.txt",
        "schema": "構造化データ",
        "meta": "メタ情報",
        "content": "コンテンツ",
        "signals": "更新シグナル",
        "ai_discovery": "AI発見性",
        "brand_entity": "ブランド",
        "negative_penalty": "減点",
    },
    "en": {
        "robots": "AI crawlers",
        "llms": "llms.txt",
        "schema": "Structured data",
        "meta": "Meta info",
        "content": "Content",
        "signals": "Freshness signals",
        "ai_discovery": "AI discovery",
        "brand_entity": "Brand",
        "negative_penalty": "Penalty",
    },
}

BAND_LABELS = {
    "ja": {
        "excellent": "非常に良好",
        "good": "良好",
        "foundation": "改善の土台あり",
        "critical": "要改善",
    },
    "en": {
        "excellent": "Excellent",
        "good": "Good",
        "foundation": "Solid foundation",
        "critical": "Needs work",
    },
}

AEO_LABELS = {
    "ja": {
        "answer_first": "結論先出し",
        "definitions": "定義文",
        "question_answers": "質問と回答",
        "evidence": "根拠・出典",
        "readability": "読みやすさ",
        "intent_coverage": "検索意図",
        "claim_risk": "主張リスク",
    },
    "en": {
        "answer_first": "Answer-first",
        "definitions": "Definitions",
        "question_answers": "Q&A",
        "evidence": "Evidence",
        "readability": "Readability",
        "intent_coverage": "Search intent",
        "claim_risk": "Claim risk",
    },
}

TEXT = {
    "ja": {
        "title": "Kurage GEO 監査レポート",
        "target": "対象URL",
        "audited_at": "監査日時",
        "score": "GEOスコア",
        "aeo_score": "AEOスコア",
        "band": "評価",
        "http": "HTTPステータス",
        "breakdown": "スコア内訳",
        "category": "項目",
        "points": "点",
        "aeo": "AEO（質問に答えられるか）",
        "aeo_ja": "日本語ページとして判定",
        "aeo_en": "英語ページとして判定",
        "aeo_unknown": "言語不明として判定",
        "aeo_none": "この監査にはAEO判定が含まれていません。再監査すると追加されます。",
        "metric": "指標",
        "recommendations": "推奨対応",
        "no_recommendations": "指摘事項はありません。",
        "details": "詳細",
        "robots_allowed": "許可されているAIクローラー",
        "robots_none": "robots.txt が見つからないか、AIクローラーの許可がありません。",
        "llms_found": "llms.txt あり",
        "llms_missing": "llms.txt なし",
        "schema_types": "検出した構造化データ",
        "schema_none": "構造化データは検出されませんでした。",
        "page_title": "ページタイトル",
        "claim_risk_note": "主張リスクは低いほど安全です。",
        "footer": "Kurage GEO で生成 ・ https://kgeo.exbridge.jp/",
        "disclaimer": (
            "本レポートは公開情報から決定論的に算出した準備度であり、"
            "外部AI検索での実際の掲載順位を保証するものではありません。"
        ),
    },
    "en": {
        "title": "Kurage GEO Audit Report",
        "target": "Target URL",
        "audited_at": "Audited at",
        "score": "GEO score",
        "aeo_score": "AEO score",
        "band": "Rating",
        "http": "HTTP status",
        "breakdown": "Score breakdown",
        "category": "Category",
        "points": "pts",
        "aeo": "AEO (can it answer questions?)",
        "aeo_ja": "Evaluated as a Japanese page",
        "aeo_en": "Evaluated as an English page",
        "aeo_unknown": "Language could not be determined",
        "aeo_none": "This audit has no AEO evaluation. Re-run the audit to add it.",
        "metric": "Metric",
        "recommendations": "Recommendations",
        "no_recommendations": "No issues found.",
        "details": "Details",
        "robots_allowed": "Allowed AI crawlers",
        "robots_none": "robots.txt was not found, or no AI crawler is allowed.",
        "llms_found": "llms.txt present",
        "llms_missing": "llms.txt missing",
        "schema_types": "Structured data found",
        "schema_none": "No structured data was detected.",
        "page_title": "Page title",
        "claim_risk_note": "For claim risk, lower is safer.",
        "footer": "Generated by Kurage GEO ・ https://kgeo.exbridge.jp/",
        "disclaimer": (
            "This report is a deterministic readiness score computed from public "
            "information. It does not guarantee ranking in any AI search product."
        ),
    },
}


# 日本語を埋め込めるTrueTypeフォントの探索先。Dockerfileで fonts-ipaexfont-gothic を
# 入れているので通常は1つ目で見つかる。KGEO_PDF_FONT で明示指定もできる。
FONT_CANDIDATES = (
    "/usr/share/fonts/opentype/ipaexfont-gothic/ipaexg.ttf",
    "/usr/share/fonts/truetype/fonts-japanese-gothic.ttf",
    "/usr/share/fonts/truetype/takao-gothic/TakaoPGothic.ttf",
    "/usr/share/fonts/truetype/vlgothic/VL-PGothic-Regular.ttf",
    "/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf",
)

PDF_FONT_NAME = "KGeoJP"


class ReportFontMissing(RuntimeError):
    """日本語を埋め込めるフォントが見つからない。PDFは出さずに明示的に失敗する。"""


def _font_path() -> str:
    override = os.environ.get("KGEO_PDF_FONT", "").strip()
    candidates = (override,) + FONT_CANDIDATES if override else FONT_CANDIDATES
    for path in candidates:
        if path and os.path.exists(path):
            return path
    raise ReportFontMissing(
        "PDF用の日本語フォントが見つかりません。fonts-ipaexfont-gothic を導入するか "
        "KGEO_PDF_FONT にTrueTypeフォントのパスを指定してください。"
    )


def _lang(value: str | None) -> str:
    return "en" if str(value or "").lower().startswith("en") else "ja"


def _jst_text(created_at: str | None) -> str:
    """保存はUTCのISO文字列。レポートの表示は必ずJSTにする。"""
    if not created_at:
        return "-"
    try:
        parsed = datetime.datetime.fromisoformat(str(created_at).replace("Z", "+00:00"))
    except ValueError:
        return str(created_at)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=datetime.timezone.utc)
    return parsed.astimezone(JST).strftime("%Y-%m-%d %H:%M JST")


def _aeo_of(result: dict) -> dict:
    # aeo が正式キー。japanese_aeo は旧監査との互換。
    aeo = result.get("aeo") or result.get("japanese_aeo") or {}
    return aeo if isinstance(aeo, dict) else {}


def _metric_value(key: str, value: Any) -> str:
    if isinstance(value, dict):
        score = value.get("score")
        return str(score) if score is not None else "-"
    return "-" if value is None else str(value)


def filename_stem(row: dict) -> str:
    """kgeo-<ホスト>-<日時> の安全なファイル名を作る。"""
    url = str((row.get("result") or {}).get("url") or "")
    host = re.sub(r"^https?://", "", url).split("/")[0] or "site"
    host = re.sub(r"[^A-Za-z0-9.-]", "-", host).strip("-") or "site"
    stamp = _jst_text(row.get("created_at")).replace(" JST", "").replace(":", "").replace(" ", "-")
    return f"kgeo-{host}-{stamp}"


def build_markdown(row: dict, lang: str | None = "ja") -> str:
    lang = _lang(lang)
    t = TEXT[lang]
    cats = CATEGORY_LABELS[lang]
    result = row.get("result") or {}
    aeo = _aeo_of(result)

    out: list[str] = []
    out.append(f"# {t['title']}")
    out.append("")
    out.append(f"- **{t['target']}**: {result.get('url') or '-'}")
    out.append(f"- **{t['audited_at']}**: {_jst_text(row.get('created_at'))}")
    band = BAND_LABELS[lang].get(str(row.get("band")), str(row.get("band") or "-"))
    out.append(f"- **{t['score']}**: {row.get('score')} / 100（{band}）")
    out.append(f"- **{t['http']}**: {row.get('http_status')}")
    if row.get("error"):
        out.append(f"- **error**: {row['error']}")
    out.append("")

    out.append(f"## {t['breakdown']}")
    out.append("")
    out.append(f"| {t['category']} | {t['points']} |")
    out.append("| --- | ---: |")
    for key, value in (row.get("score_breakdown") or {}).items():
        out.append(f"| {cats.get(key, key)} | {value} |")
    out.append("")

    out.append(f"## {t['aeo']}")
    out.append("")
    if not aeo.get("checked"):
        out.append(t["aeo_none"])
    else:
        analyzed = str(aeo.get("analyzed_as") or aeo.get("language") or "")
        judged = t["aeo_ja"] if analyzed == "ja" else t["aeo_en"] if analyzed == "en" else t["aeo_unknown"]
        aeo_band = BAND_LABELS[lang].get(str(aeo.get("band")), str(aeo.get("band") or "-"))
        out.append(f"- **{t['aeo_score']}**: {aeo.get('score')} / 100（{aeo_band}）")
        out.append(f"- {judged}")
        if aeo.get("notice"):
            out.append(f"- {aeo['notice']}")
        out.append("")
        metrics = aeo.get("metrics") or {}
        if metrics:
            out.append(f"| {t['metric']} | {t['points']} |")
            out.append("| --- | ---: |")
            for key, value in metrics.items():
                out.append(f"| {AEO_LABELS[lang].get(key, key)} | {_metric_value(key, value)} |")
            out.append("")
            out.append(t["claim_risk_note"])
    out.append("")

    out.append(f"## {t['recommendations']}")
    out.append("")
    recs = row.get("recommendations_ja") or []
    if recs:
        for item in recs:
            out.append(f"- {item}")
    else:
        out.append(t["no_recommendations"])
    out.append("")

    out.append(f"## {t['details']}")
    out.append("")
    robots = result.get("robots") or {}
    allowed = robots.get("bots_allowed") or []
    if allowed:
        out.append(f"**{t['robots_allowed']}** ({len(allowed)})")
        out.append("")
        out.append(", ".join(str(b) for b in allowed))
    else:
        out.append(t["robots_none"])
    out.append("")
    llms = result.get("llms") or {}
    out.append(f"- {t['llms_found'] if llms.get('found') else t['llms_missing']}")
    schema_types = (result.get("schema") or {}).get("found_types") or []
    if schema_types:
        out.append(f"- {t['schema_types']}: {', '.join(str(s) for s in schema_types)}")
    else:
        out.append(f"- {t['schema_none']}")
    title_text = (result.get("meta") or {}).get("title_text")
    if title_text:
        out.append(f"- {t['page_title']}: {title_text}")
    out.append("")

    out.append("---")
    out.append("")
    out.append(t["disclaimer"])
    out.append("")
    out.append(t["footer"])
    out.append("")
    return "\n".join(out)


def build_pdf(row: dict, lang: str | None = "ja") -> bytes:
    """Markdownと同じ内容をPDFにする。日本語は内蔵CIDフォントで描画する。"""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT, TA_RIGHT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.platypus import (
        HRFlowable,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    # フォントは埋め込む。内蔵CIDフォントだと閲覧環境によって英数字が豆腐になる。
    font_name = PDF_FONT_NAME
    try:
        pdfmetrics.getFont(font_name)
    except Exception:
        pdfmetrics.registerFont(TTFont(font_name, _font_path()))

    lang = _lang(lang)
    t = TEXT[lang]
    cats = CATEGORY_LABELS[lang]
    result = row.get("result") or {}
    aeo = _aeo_of(result)

    teal = colors.HexColor("#12a99f")
    ink = colors.HexColor("#17324d")
    muted = colors.HexColor("#64788a")

    body = ParagraphStyle("body", fontName=font_name, fontSize=9.5, leading=15,
                          textColor=ink, alignment=TA_LEFT)
    h1 = ParagraphStyle("h1", parent=body, fontSize=17, leading=24, textColor=teal,
                        spaceAfter=4)
    h2 = ParagraphStyle("h2", parent=body, fontSize=12.5, leading=19, textColor=teal,
                        spaceBefore=12, spaceAfter=5)
    small = ParagraphStyle("small", parent=body, fontSize=8, leading=12, textColor=muted)
    bullet = ParagraphStyle("bullet", parent=body, leftIndent=12, bulletIndent=2,
                            bulletFontName=font_name, bulletFontSize=9.5, spaceAfter=2)
    # 表の数値列。Paragraphは自前の配置を持つのでTableStyleのALIGNだけでは右寄せにならない
    num = ParagraphStyle("num", parent=body, alignment=TA_RIGHT)

    def esc(value: Any) -> str:
        return (str(value if value is not None else "-")
                .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))

    def table(rows: list[list[str]]) -> Table:
        tbl = Table(rows, colWidths=[95 * mm, 30 * mm], hAlign="LEFT")
        tbl.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, -1), font_name),
            ("FONTSIZE", (0, 0), (-1, -1), 9.5),
            ("TEXTCOLOR", (0, 0), (-1, -1), ink),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f5fbfb")),
            ("ALIGN", (1, 0), (1, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#dbe6ee")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        return tbl

    story: list[Any] = [Paragraph(esc(t["title"]), h1)]
    band = BAND_LABELS[lang].get(str(row.get("band")), str(row.get("band") or "-"))
    story.append(Paragraph(
        f"{esc(t['target'])}: {esc(result.get('url'))}<br/>"
        f"{esc(t['audited_at'])}: {esc(_jst_text(row.get('created_at')))}<br/>"
        f"{esc(t['score'])}: <b>{esc(row.get('score'))}</b> / 100（{esc(band)}）　"
        f"{esc(t['http'])}: {esc(row.get('http_status'))}", body))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#dbe6ee")))

    story.append(Paragraph(esc(t["breakdown"]), h2))
    rows = [[Paragraph(f"<b>{esc(t['category'])}</b>", body),
             Paragraph(f"<b>{esc(t['points'])}</b>", num)]]
    for key, value in (row.get("score_breakdown") or {}).items():
        rows.append([Paragraph(esc(cats.get(key, key)), body), Paragraph(esc(value), num)])
    story.append(table(rows))

    story.append(Paragraph(esc(t["aeo"]), h2))
    if not aeo.get("checked"):
        story.append(Paragraph(esc(t["aeo_none"]), body))
    else:
        analyzed = str(aeo.get("analyzed_as") or aeo.get("language") or "")
        judged = t["aeo_ja"] if analyzed == "ja" else t["aeo_en"] if analyzed == "en" else t["aeo_unknown"]
        aeo_band = BAND_LABELS[lang].get(str(aeo.get("band")), str(aeo.get("band") or "-"))
        story.append(Paragraph(
            f"{esc(t['aeo_score'])}: <b>{esc(aeo.get('score'))}</b> / 100（{esc(aeo_band)}）　{esc(judged)}", body))
        if aeo.get("notice"):
            story.append(Paragraph(esc(aeo["notice"]), small))
        story.append(Spacer(1, 4))
        metrics = aeo.get("metrics") or {}
        if metrics:
            rows = [[Paragraph(f"<b>{esc(t['metric'])}</b>", body),
                     Paragraph(f"<b>{esc(t['points'])}</b>", num)]]
            for key, value in metrics.items():
                rows.append([Paragraph(esc(AEO_LABELS[lang].get(key, key)), body),
                             Paragraph(esc(_metric_value(key, value)), num)])
            story.append(table(rows))
            story.append(Spacer(1, 3))
            story.append(Paragraph(esc(t["claim_risk_note"]), small))

    story.append(Paragraph(esc(t["recommendations"]), h2))
    recs = row.get("recommendations_ja") or []
    if recs:
        for item in recs:
            story.append(Paragraph(esc(item), bullet, bulletText="・"))
    else:
        story.append(Paragraph(esc(t["no_recommendations"]), body))

    story.append(Paragraph(esc(t["details"]), h2))
    robots = result.get("robots") or {}
    allowed = robots.get("bots_allowed") or []
    if allowed:
        story.append(Paragraph(f"<b>{esc(t['robots_allowed'])}</b>（{len(allowed)}）", body))
        story.append(Paragraph(esc(", ".join(str(b) for b in allowed)), small))
    else:
        story.append(Paragraph(esc(t["robots_none"]), body))
    story.append(Spacer(1, 4))
    llms = result.get("llms") or {}
    story.append(Paragraph(esc(t["llms_found"] if llms.get("found") else t["llms_missing"]), bullet,
                           bulletText="・"))
    schema_types = (result.get("schema") or {}).get("found_types") or []
    story.append(Paragraph(
        esc(f"{t['schema_types']}: {', '.join(str(s) for s in schema_types)}") if schema_types
        else esc(t["schema_none"]), bullet, bulletText="・"))
    title_text = (result.get("meta") or {}).get("title_text")
    if title_text:
        story.append(Paragraph(esc(f"{t['page_title']}: {title_text}"), bullet, bulletText="・"))

    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#dbe6ee")))
    story.append(Paragraph(esc(t["disclaimer"]), small))
    story.append(Paragraph(esc(t["footer"]), small))

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
        title=f"{t['title']} - {result.get('url') or ''}", author="Kurage GEO",
    )
    doc.build(story)
    return buffer.getvalue()
